# Opcional - O nome do fluxo de trabalho conforme aparecerá na guia "Ações" do repositório GitHub. Se este campo for omitido, o nome do arquivo de fluxo de trabalho será usado.
name: learn-github-actions

# Opcional - O nome das execuções de fluxo de trabalho geradas a partir do fluxo de trabalho, que aparecerá na lista de execuções de fluxo de trabalho na guia "Ações" do seu repositório. Este exemplo usa uma expressão com o contexto `github` para exibir o nome de usuário do ator que acionou a execução do fluxo de trabalho. Para obter mais informações, consulte "[AUTOTITLE](/actions/using-workflows/workflow-syntax-for-github-actions#run-name)."
run-name: ${{ github.actor }}

on: [push]
jobs:
  check-bats-version:
    runs-on: ubunt-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
